spring.application.name=PayFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configuração do Flyway
spring.flyway.enabled=true